#! /bin/bash

DOCKER_NAME="implcde_serov" # username in container
CONTAINER_NAME=$USER"-implcde_serov" # name of container
SRC="/ImplicitCDE/" # source directory (supposedly, this repo's path is /home/${USER}/${SRC})

# to get these values type "id" in shell termilal
DOCKER_USER_ID=4200274
DOCKER_GROUP_ID=4200274

